node('dind-node') {
  withMaven(maven:'M3') {
    stage('Checkout') {
      git url: 'https://github.com/MEHIKE/zuul_proxy.git', credentialsId: 'mehike', branch: 'master'
    }
    stage('Build') {
      dir('zuul_proxy') {
        sh 'mvn clean install'
        def pom = readMavenPom file:'pom.xml'
        print pom.version
        env.version = pom.version
        currentBuild.description = "Release: ${env.version}"
      }
    }
    stage('Image') {
      dir ('zuul_proxy') {
        docker.withRegistry('https://192.168.99.100:5000') {
          def app = docker.build "mehike/zuul-proxy:${env.version}"
          app.push()
        }
      }
    }
  }
}