apiVersion: v1
kind: Service
metadata:
  name: zuul
  labels:
    app: zuul
spec:
  externalIPs:
  - 192.168.1.156
  - 88.196.63.92
  ports:
  - port: 8060
    protocol: TCP
    targetPort: 8060
  selector:
    app: zuul
  type: NodePort
